// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgnsPi37tPvBGlw3qyoRqGyLUwxyR9Q48',
    appId: '1:1095203254006:web:c9dd30e9567a5f13da86d7',
    messagingSenderId: '1095203254006',
    projectId: 'invue-41d17',
    authDomain: 'invue-41d17.firebaseapp.com',
    storageBucket: 'invue-41d17.appspot.com',
    measurementId: 'G-PQ21D22VV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbyjYqyxefqyd-vK4JIDK4b2ptazRTx8',
    appId: '1:1095203254006:android:07ade63d5c8ee8d4da86d7',
    messagingSenderId: '1095203254006',
    projectId: 'invue-41d17',
    storageBucket: 'invue-41d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7EBjyfBdA0_zXEmKnWx2nBhyR1tKZQc',
    appId: '1:1095203254006:ios:1925946a4e7d80f0da86d7',
    messagingSenderId: '1095203254006',
    projectId: 'invue-41d17',
    storageBucket: 'invue-41d17.appspot.com',
    iosBundleId: 'com.example.invue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7EBjyfBdA0_zXEmKnWx2nBhyR1tKZQc',
    appId: '1:1095203254006:ios:1925946a4e7d80f0da86d7',
    messagingSenderId: '1095203254006',
    projectId: 'invue-41d17',
    storageBucket: 'invue-41d17.appspot.com',
    iosBundleId: 'com.example.invue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgnsPi37tPvBGlw3qyoRqGyLUwxyR9Q48',
    appId: '1:1095203254006:web:278c4f0565c91b31da86d7',
    messagingSenderId: '1095203254006',
    projectId: 'invue-41d17',
    authDomain: 'invue-41d17.firebaseapp.com',
    storageBucket: 'invue-41d17.appspot.com',
    measurementId: 'G-N92DR5NS7J',
  );
}
